export const CLIENT_BUILTIN_ACTIVITIES = [
  { id: 'builtin:our-vids', key: 'our-vids', iconKey: 'our-vids', name: 'OurVids', description: 'Synchronized video watching with queue and voting. YouTube and video file support.', category: 'Media', icon: 'video', participantCap: 64 },
  { id: 'builtin:ready-check', key: 'ready-check', iconKey: 'ready-check', name: 'Ready Check', description: 'Fast ready confirmations for groups.', category: 'Utility', icon: 'check', participantCap: 128 },
  { id: 'builtin:soundboard-cues', key: 'soundboard-cues', iconKey: 'soundboard-cues', name: 'Soundboard Cues', description: 'Trigger and share reactive sound cues.', category: 'Music', icon: 'audio', participantCap: 64 },
  { id: 'builtin:sequencer', key: 'sequencer', iconKey: 'sequencer', name: 'Sequencer', description: 'Simple 8-step beat sequencer.', category: 'Music', icon: 'grid', participantCap: 32 },
  { id: 'builtin:bytebeat', key: 'bytebeat', iconKey: 'bytebeat', name: 'Bytebeat', description: 'Algorithmic music composer using mathematical formulas. Write one-liner code to generate 8-bit chiptune audio in real-time. Supports bytebeat, signed, float, and funcbeat modes.', category: 'Music', icon: 'audio', participantCap: 32 },
  { id: 'builtin:colabcreate', key: 'colabcreate', iconKey: 'colabcreate', name: 'ColabCreate', description: 'Full collaborative DAW with advanced synth oscillators, piano roll, drum kits, synced sample streaming, track arrangement, mixer, MIDI support, and export to WAV/MIDI/JSON.', category: 'Music', icon: 'daw', participantCap: 16 },
  { id: 'builtin:sketch-duel', key: 'sketch-duel', iconKey: 'sketch-duel', name: 'Sketch Duel', description: 'Fast timed doodle battles with judging.', category: 'Creative', icon: 'sketch', participantCap: 8 },
  { id: 'builtin:collaborative-drawing', key: 'collaborative-drawing', iconKey: 'collaborative-drawing', name: 'Drawing Board', description: 'Real-time collaborative drawing canvas. See everyone\'s cursor, draw together, export to PNG or project files.', category: 'Creative', icon: 'draw', participantCap: 16 },
  { id: 'builtin:collaborative-drawing-3d', key: 'collaborative-drawing-3d', iconKey: 'collaborative-drawing-3d', name: 'World Sketch 3D', description: 'Collaborative Three.js 3D drawing and scene building. Paint floating strokes in space, place primitives, orbit the room together, and build shared spatial sketches in real time.', category: 'Creative', icon: '3d-modeling', participantCap: 12 },
  { id: 'builtin:pixel-art', key: 'pixel-art', iconKey: 'pixel-art', name: 'Pixel Art Board', description: 'Shared pixel canvas with palette tools and history timeline.', category: 'Creative', icon: 'pixels', participantCap: 32 },
  { id: 'builtin:poker-night', key: 'poker-night', iconKey: 'poker-night', name: 'Poker Night', description: 'Texas Hold\'em poker with friends. Bet, raise, and bluff your way to victory!', category: 'Games', icon: 'poker', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:chess-arena', key: 'chess-arena', iconKey: 'chess-arena', name: 'Chess Arena', description: 'Multiplayer chess with spectators.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:tic-tac-toe', key: 'tic-tac-toe', iconKey: 'tic-tac-toe', name: 'Tic Tac Toe', description: 'Classic multiplayer grid duel.', category: 'Games', icon: 'tic-tac-toe', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:connect-four', key: 'connect-four', iconKey: 'connect-four', name: 'Connect Four', description: 'Drop-disc strategy game.', category: 'Games', icon: 'connect-four', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:minigolf', key: 'minigolf', iconKey: 'minigolf', name: 'MiniGolf', description: 'Shared mini golf with stylized 3D courses and rotating turns.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:8ball-pool', key: '8ball-pool', iconKey: '8ball-pool', name: '8Ball Pool', description: 'Top-down 8-ball pool with shared racks, turn order, solids vs stripes, and synchronized shot playback.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:checkers', key: 'checkers', iconKey: 'checkers', name: 'Checkers', description: 'Shared checkers with kings, captures, and spectator support.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:reversi', key: 'reversi', iconKey: 'reversi', name: 'Reversi', description: 'Corner-driven disc flipping duel with synchronized turn flow.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:gomoku', key: 'gomoku', iconKey: 'gomoku', name: 'Gomoku', description: 'Five-in-a-row strategy on a large shared board.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:dots-and-boxes', key: 'dots-and-boxes', iconKey: 'dots-and-boxes', name: 'Dots & Boxes', description: 'Box-claiming line game with chained bonus turns.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:memory-match', key: 'memory-match', iconKey: 'memory-match', name: 'Memory Match', description: 'Shared pair-flipping memory duel with score tracking.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:minesweeper-party', key: 'minesweeper-party', iconKey: 'minesweeper-party', name: 'Minesweeper Party', description: 'Collaborative shared minefield clearing with flags and reveals.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 1, gameType: 'co-op' },
  { id: 'builtin:party-2048', key: 'party-2048', iconKey: 'party-2048', name: '2048 Party', description: 'A shared sliding 2048 board for the whole room.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 1, gameType: 'co-op' },
  { id: 'builtin:mancala', key: 'mancala', iconKey: 'mancala', name: 'Mancala', description: 'Stone-sowing pit strategy with captures and extra turns.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:sky-derby-3d', key: 'sky-derby-3d', iconKey: 'sky-derby-3d', name: 'Sky Derby 3D', description: 'Three.js checkpoint racing across a huge cloud circuit with craft selection, ready states, and live flight controls.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 2, gameType: 'action' },
  { id: 'builtin:tower-stack-3d', key: 'tower-stack-3d', iconKey: 'tower-stack-3d', name: 'Tower Stack 3D', description: 'Competitive skyline stacking with adjacency scoring bonuses.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:skyline-checkers-3d', key: 'skyline-checkers-3d', iconKey: 'skyline-checkers-3d', name: 'Skyline Checkers 3D', description: 'Classic checkers staged on a dramatic Three.js rooftop arena with animated capture lanes and spectator-friendly camera sweeps.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:lava-checkers-3d', key: 'lava-checkers-3d', iconKey: 'lava-checkers-3d', name: 'Lava Checkers 3D', description: 'Diagonal capture duels on a molten Three.js board with glowing tiles, heat shimmer, and chunky 3D pieces.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:glacier-checkers-3d', key: 'glacier-checkers-3d', iconKey: 'glacier-checkers-3d', name: 'Glacier Checkers 3D', description: 'A frozen checkers table rendered in Three.js with icy lighting, animated crowns, and mirrored spectator angles.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:orbit-reversi-3d', key: 'orbit-reversi-3d', iconKey: 'orbit-reversi-3d', name: 'Orbit Reversi 3D', description: 'Disc-flipping strategy on a hovering Three.js station board with orbit lights and tactile 3D tokens.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:prism-reversi-3d', key: 'prism-reversi-3d', iconKey: 'prism-reversi-3d', name: 'Prism Reversi 3D', description: 'Play Reversi inside a glassy Three.js prism chamber with refractive board art and animated flip trails.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:reef-reversi-3d', key: 'reef-reversi-3d', iconKey: 'reef-reversi-3d', name: 'Reef Reversi 3D', description: 'A coral-lit Three.js Reversi arena with underwater ambience, soft caustics, and chunky shell-like discs.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:zen-gomoku-3d', key: 'zen-gomoku-3d', iconKey: 'zen-gomoku-3d', name: 'Zen Gomoku 3D', description: 'Five-in-a-row on a serene Three.js stone garden board with smooth camera motion and spatial placement cues.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:neon-gomoku-3d', key: 'neon-gomoku-3d', iconKey: 'neon-gomoku-3d', name: 'Neon Gomoku 3D', description: 'Fast tactical Gomoku on a glowing cyber grid rendered as a dramatic Three.js tabletop arena.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:asteroid-gomoku-3d', key: 'asteroid-gomoku-3d', iconKey: 'asteroid-gomoku-3d', name: 'Asteroid Gomoku 3D', description: 'A space-themed Three.js Gomoku board suspended over debris fields with bold piece drops and orbital lighting.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:neon-dots-3d', key: 'neon-dots-3d', iconKey: 'neon-dots-3d', name: 'Neon Dots 3D', description: 'Dots & Boxes rebuilt as a glowing Three.js lattice with animated edge beams and scoring pulses.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:blueprint-boxes-3d', key: 'blueprint-boxes-3d', iconKey: 'blueprint-boxes-3d', name: 'Blueprint Boxes 3D', description: 'A studio-blueprint take on Dots & Boxes with raised Three.js pegs, drafting-grid atmosphere, and clean spatial scoring.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:laser-lattice-3d', key: 'laser-lattice-3d', iconKey: 'laser-lattice-3d', name: 'Laser Lattice 3D', description: 'Three.js box-claiming duels played on a laser frame structure with reactive beams and pulsing cell ownership.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:memory-vault-3d', key: 'memory-vault-3d', iconKey: 'memory-vault-3d', name: 'Memory Vault 3D', description: 'Pair-matching played on a dramatic Three.js vault floor with flipping 3D cards and shared spectator angles.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:crystal-pairs-3d', key: 'crystal-pairs-3d', iconKey: 'crystal-pairs-3d', name: 'Crystal Pairs 3D', description: 'A shimmering Three.js memory arena where gem slabs rotate, glow, and reveal shared pair streaks.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:holo-match-3d', key: 'holo-match-3d', iconKey: 'holo-match-3d', name: 'Holo Match 3D', description: 'Memory matching inside a holographic Three.js cube room with animated reveal waves and score bursts.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:void-sweeper-3d', key: 'void-sweeper-3d', iconKey: 'void-sweeper-3d', name: 'Void Sweeper 3D', description: 'Co-op Three.js minesweeper in a floating sci-fi chamber with raised tiles, flag props, and shared camera drama.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 1, gameType: 'co-op' },
  { id: 'builtin:reef-sweeper-3d', key: 'reef-sweeper-3d', iconKey: 'reef-sweeper-3d', name: 'Reef Sweeper 3D', description: 'Collaborative minesweeper on an underwater Three.js board with coral markers, buoy flags, and soft aquatic motion.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 1, gameType: 'co-op' },
  { id: 'builtin:ruins-sweeper-3d', key: 'ruins-sweeper-3d', iconKey: 'ruins-sweeper-3d', name: 'Ruins Sweeper 3D', description: 'Shared minefield clearing in a weathered Three.js ruin plaza with stone tiles, dust bursts, and co-op pacing.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 1, gameType: 'co-op' },
  { id: 'builtin:reactor-2048-3d', key: 'reactor-2048-3d', iconKey: 'reactor-2048-3d', name: 'Reactor 2048 3D', description: 'A shared Three.js 2048 reactor core where tiles rise as animated blocks and merges trigger energy bursts.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 1, gameType: 'co-op' },
  { id: 'builtin:monolith-2048-3d', key: 'monolith-2048-3d', iconKey: 'monolith-2048-3d', name: 'Monolith 2048 3D', description: 'Slide number blocks across a monumental Three.js chamber with towering merge stacks and bold score feedback.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 1, gameType: 'co-op' },
  { id: 'builtin:prism-2048-3d', key: 'prism-2048-3d', iconKey: 'prism-2048-3d', name: 'Prism 2048 3D', description: 'A luminous Three.js 2048 board with translucent cubes, animated merge trails, and roomwide glow cues.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 1, gameType: 'co-op' },
  { id: 'builtin:temple-mancala-3d', key: 'temple-mancala-3d', iconKey: 'temple-mancala-3d', name: 'Temple Mancala 3D', description: 'Stone-sowing strategy in a carved Three.js temple board with bead physics, elevated pits, and ritual ambience.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:nebula-mancala-3d', key: 'nebula-mancala-3d', iconKey: 'nebula-mancala-3d', name: 'Nebula Mancala 3D', description: 'A cosmic Three.js mancala table with floating marbles, soft orbital lighting, and dramatic capture effects.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:relic-mancala-3d', key: 'relic-mancala-3d', iconKey: 'relic-mancala-3d', name: 'Relic Mancala 3D', description: 'Ancient-relief mancala reimagined as a tactile Three.js artifact table with carved bowls and shared move focus.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:canyon-derby-3d', key: 'canyon-derby-3d', iconKey: 'canyon-derby-3d', name: 'Canyon Derby 3D', description: 'An arcade-style Three.js lane runner with canyon walls, moving hazards, and shared head-to-head race pacing.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:neon-derby-3d', key: 'neon-derby-3d', iconKey: 'neon-derby-3d', name: 'Neon Derby 3D', description: 'A cyber-lit Three.js derby track with glowing lanes, fast hazard calls, and stylized competitive camera beats.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:storm-runner-3d', key: 'storm-runner-3d', iconKey: 'storm-runner-3d', name: 'Storm Runner 3D', description: 'Take turns navigating a storm-battered Three.js race corridor with boost choices, hazard rows, and dramatic skies.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:skyline-stack-3d', key: 'skyline-stack-3d', iconKey: 'skyline-stack-3d', name: 'Skyline Stack 3D', description: 'Build vertical districts in a polished Three.js skyline diorama with animated adjacency bonuses and ownership lighting.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:crystal-stack-3d', key: 'crystal-stack-3d', iconKey: 'crystal-stack-3d', name: 'Crystal Stack 3D', description: 'Competitive 3D tower stacking on a reflective crystal plateau with glowing block layers and combo callouts.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:magma-stack-3d', key: 'magma-stack-3d', iconKey: 'magma-stack-3d', name: 'Magma Stack 3D', description: 'Raise volcanic tower clusters in a fiery Three.js arena where each stack layer pulses with heat and score energy.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:voltcraft', key: 'voltcraft', iconKey: 'voltcraft', name: 'VoltCraft', description: 'Shared voxel sandbox with 16x16 chunks, mining, crafting, creative or survival play, and multiplayer block sync.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 1, gameType: 'sandbox' },
  { id: 'builtin:voltverse', key: 'voltverse', iconKey: 'voltverse', name: 'VoltVerse', description: 'Full 3D social VR platform with shared avatars, worlds, custom shaders, level editor, avatar editor, portals, triggers, teleportation, and real-time P2P networking. Supports VR and desktop.', category: 'Social', icon: 'vr', participantCap: 64 },
  { id: 'builtin:voltverse-creator', key: 'voltverse-creator', iconKey: 'voltverse-creator', name: 'VoltVerse Creator', description: 'Collaborative WYSIWYG world and avatar editor. Create custom 3D worlds with objects, imported models, lighting, portals, triggers, shaders, and shared editing. Design avatars with customizable body parts, colors, presets, and imported 3D models. Export as .voltworld or .voltavatar files.', category: 'Creative', icon: 'edit', participantCap: 8 },
  { id: 'builtin:collab-3d-modeling', key: 'collab-3d-modeling', iconKey: 'collab-3d-modeling', name: '3D Modeling Studio', description: 'Real-time collaborative 3D modeling with Three.js. Add primitives, transform objects, apply materials, upload reference images, and build 3D models together with your group.', category: 'Creative', icon: '3d-modeling', participantCap: 8 },
  { id: 'builtin:templevolt', key: 'templevolt', iconKey: 'templevolt', name: 'TempleVolt', description: 'A canvas-driven parody shell inspired by TempleOS aesthetics. Fake commands, joke apps, retro windows, and shared terminal chaos. Not a real emulator.', category: 'Creative', icon: 'board', participantCap: 16 },
  { id: 'builtin:sky-raid', key: 'sky-raid', iconKey: 'sky-raid', name: 'Sky Raid', description: 'Large-scale Three.js dogfighting with craft loadouts, ready flow, sounds, pickups, and ballistic projectiles.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 1, gameType: 'action' },
  { id: 'builtin:retro-rift-93', key: 'retro-rift-93', iconKey: 'retro-rift-93', name: "Retro Rift '93", description: 'Original retro multiplayer deathmatch with software-style raycasting, fast strafes, and synth-driven combat.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 1, gameType: 'action' },
  { id: 'builtin:defcon-3', key: 'defcon-3', iconKey: 'defcon-3', name: 'DEFCON 3', description: 'A Three.js cold-war strategy crisis sim with asymmetric nations, FM tension music, blocs, diplomacy, and automatic NULLFIRE launch when the shared DEFCON clock hits 1.', category: 'Games', icon: 'board', participantCap: 12, minPlayers: 1, gameType: 'strategy' },
  { id: 'builtin:timedilationchess', key: 'timedilationchess', iconKey: 'timedilationchess', name: 'Time Dilation Chess', description: '5D Chess with Multiverse Time Travel - A 2D canvas-based chess game with zoom and pan controls. Inspired by the mind-bending chess variant with multiverse mechanics.', category: 'Games', icon: 'board', participantCap: 16, minPlayers: 2, gameType: 'turn-based' },
  { id: 'builtin:anarchy-chess', key: 'anarchy-chess', iconKey: 'anarchy-chess', name: 'Anarchy Chess', description: '4-player real-time chess with no turns! Move any piece anytime with a 0.5s cooldown per player. Chaos and strategy collide in this fast-paced chess variant.', category: 'Games', icon: 'board', participantCap: 8, minPlayers: 2, gameType: 'action' }
].map((item, idx) => ({
  ...item,
  isBuiltinClient: true,
  isDefault: false,
  defaultRank: idx + 1,
  visibility: 'public',
  oauthRequired: false,
  scopes: ['activities:read', 'activities:join', 'activities:state:write', 'activities:events:write', 'activities:p2p'],
  p2pPolicy: { enabled: true, preferred: true, maxPeers: 32, fallbackToServerRelay: true },
  soundPack: { profile: 'cinematic', enabledByDefault: true, volume: 0.82, cues: ['session_created', 'session_joined', 'session_left', 'round_start', 'round_end', 'score_update', 'ready_check', 'error', 'game_start', 'game_end', 'player_join', 'player_leave', 'your_turn', 'countdown', 'timer_start', 'timer_end', 'victory', 'defeat', 'draw', 'turn_switch', 'move_valid', 'move_invalid', 'combo', 'streak', 'powerup', 'damage', 'heal', 'level_up', 'achievement_unlock', 'button_click', 'menu_open', 'menu_close', 'popup_open', 'popup_close', 'selection_change', 'spectator_join', 'spectator_leave', 'host_transfer', 'player_ready', 'player_not_ready', 'round_win', 'round_loss', 'sudden_death', 'overtime', 'intermission', 'pause', 'resume', 'coin_collect', 'xp_gain'] },
  launchUrl: `builtin://${item.key}`,
  originHost: 'client',
  createdAt: '2026-03-01T00:00:00.000Z',
  updatedAt: '2026-03-01T00:00:00.000Z'
}))

export const CLIENT_BUILTIN_BY_ID = Object.fromEntries(CLIENT_BUILTIN_ACTIVITIES.map(item => [item.id, item]))

const BUILTIN_DEFINITION_ALIASES = {
  'builtin:ourvids': 'builtin:our-vids',
  'builtin:drawing-board': 'builtin:collaborative-drawing',
  'builtin:daw': 'builtin:colabcreate',
  'builtin:colab-create': 'builtin:colabcreate',
  'builtin:byte-beat': 'builtin:bytebeat',
  'our-vids': 'builtin:our-vids',
  'ready-check': 'builtin:ready-check',
  'soundboard-cues': 'builtin:soundboard-cues',
  'sequencer': 'builtin:sequencer',
  'bytebeat': 'builtin:bytebeat',
  'byte-beat': 'builtin:bytebeat',
  'sketch-duel': 'builtin:sketch-duel',
  'collaborative-drawing-3d': 'builtin:collaborative-drawing-3d',
  'drawing-3d': 'builtin:collaborative-drawing-3d',
  'world-sketch-3d': 'builtin:collaborative-drawing-3d',
  'pixel-art': 'builtin:pixel-art',
  'poker-night': 'builtin:poker-night',
  'chess-arena': 'builtin:chess-arena',
  'tic-tac-toe': 'builtin:tic-tac-toe',
  'connect-four': 'builtin:connect-four',
  'minigolf': 'builtin:minigolf',
  '8ball-pool': 'builtin:8ball-pool',
  '8-ball-pool': 'builtin:8ball-pool',
  'eightball-pool': 'builtin:8ball-pool',
  'eight-ball-pool': 'builtin:8ball-pool',
  'checkers': 'builtin:checkers',
  'reversi': 'builtin:reversi',
  'gomoku': 'builtin:gomoku',
  'dots-and-boxes': 'builtin:dots-and-boxes',
  'dots-boxes': 'builtin:dots-and-boxes',
  'memory-match': 'builtin:memory-match',
  'minesweeper-party': 'builtin:minesweeper-party',
  'party-2048': 'builtin:party-2048',
  'mancala': 'builtin:mancala',
  'sky-derby-3d': 'builtin:sky-derby-3d',
  'asteroid-run-3d': 'builtin:sky-derby-3d',
  'canyon-wing': 'builtin:sky-derby-3d',
  'cloud-circuit': 'builtin:sky-derby-3d',
  'volcano-rush': 'builtin:sky-derby-3d',
  'orbital-strike': 'builtin:sky-raid',
  'glacier-gunners': 'builtin:sky-raid',
  'island-patrol': 'builtin:sky-raid',
  'storm-chasers-3d': 'builtin:sky-derby-3d',
  'desert-ace': 'builtin:sky-raid',
  'neon-drone-arena': 'builtin:sky-raid',
  'tower-stack-3d': 'builtin:tower-stack-3d',
  'skyline-checkers-3d': 'builtin:skyline-checkers-3d',
  'lava-checkers-3d': 'builtin:lava-checkers-3d',
  'glacier-checkers-3d': 'builtin:glacier-checkers-3d',
  'orbit-reversi-3d': 'builtin:orbit-reversi-3d',
  'prism-reversi-3d': 'builtin:prism-reversi-3d',
  'reef-reversi-3d': 'builtin:reef-reversi-3d',
  'zen-gomoku-3d': 'builtin:zen-gomoku-3d',
  'neon-gomoku-3d': 'builtin:neon-gomoku-3d',
  'asteroid-gomoku-3d': 'builtin:asteroid-gomoku-3d',
  'neon-dots-3d': 'builtin:neon-dots-3d',
  'blueprint-boxes-3d': 'builtin:blueprint-boxes-3d',
  'laser-lattice-3d': 'builtin:laser-lattice-3d',
  'memory-vault-3d': 'builtin:memory-vault-3d',
  'crystal-pairs-3d': 'builtin:crystal-pairs-3d',
  'holo-match-3d': 'builtin:holo-match-3d',
  'void-sweeper-3d': 'builtin:void-sweeper-3d',
  'reef-sweeper-3d': 'builtin:reef-sweeper-3d',
  'ruins-sweeper-3d': 'builtin:ruins-sweeper-3d',
  'reactor-2048-3d': 'builtin:reactor-2048-3d',
  'monolith-2048-3d': 'builtin:monolith-2048-3d',
  'prism-2048-3d': 'builtin:prism-2048-3d',
  'temple-mancala-3d': 'builtin:temple-mancala-3d',
  'nebula-mancala-3d': 'builtin:nebula-mancala-3d',
  'relic-mancala-3d': 'builtin:relic-mancala-3d',
  'canyon-derby-3d': 'builtin:canyon-derby-3d',
  'neon-derby-3d': 'builtin:neon-derby-3d',
  'storm-runner-3d': 'builtin:storm-runner-3d',
  'skyline-stack-3d': 'builtin:skyline-stack-3d',
  'crystal-stack-3d': 'builtin:crystal-stack-3d',
  'magma-stack-3d': 'builtin:magma-stack-3d',
  'voltcraft': 'builtin:voltcraft',
  'volt-craft': 'builtin:voltcraft',
  'templevolt': 'builtin:templevolt',
  'templevolt-os': 'builtin:templevolt',
  'holy-shell': 'builtin:templevolt',
  'collaborative-drawing': 'builtin:collaborative-drawing',
  'daw-sequencer': 'builtin:colabcreate',
  'daw-studio': 'builtin:colabcreate',
  'colabcreate': 'builtin:colabcreate',
  'voltverse': 'builtin:voltverse',
  'volt-verse': 'builtin:voltverse',
  'voltverse3d': 'builtin:voltverse',
  'voltverse-creator': 'builtin:voltverse-creator',
  'voltverse-creator': 'builtin:voltverse-creator',
  'vv-creator': 'builtin:voltverse-creator',
  'flight-sim': 'builtin:sky-raid',
  'flight-simulator': 'builtin:sky-raid',
  'builtin:retro-rift': 'builtin:retro-rift-93',
  'builtin:rift93': 'builtin:retro-rift-93',
  'retro-rift-93': 'builtin:retro-rift-93',
  'retro-rift': 'builtin:retro-rift-93',
  'rift93': 'builtin:retro-rift-93',
  'builtin:defcon3': 'builtin:defcon-3',
  'builtin:nullfire': 'builtin:defcon-3',
  'defcon-3': 'builtin:defcon-3',
  'defcon3': 'builtin:defcon-3',
  'nullfire': 'builtin:defcon-3',
  'collab-3d-modeling': 'builtin:collab-3d-modeling',
  '3d-modeling': 'builtin:collab-3d-modeling',
  'collab3d': 'builtin:collab-3d-modeling',
  'anarchy-chess': 'builtin:anarchy-chess',
  'anarchychess': 'builtin:anarchy-chess',
  'builtin:anarchychess': 'builtin:anarchy-chess',
  '4-player-chess': 'builtin:anarchy-chess',
  'realtime-chess': 'builtin:anarchy-chess'
}

export const normalizeBuiltinDefinitionId = (activityId) => {
  if (typeof activityId !== 'string') return null
  const normalized = activityId.trim()
  if (!normalized) return null
  if (CLIENT_BUILTIN_BY_ID[normalized]) return normalized
  return BUILTIN_DEFINITION_ALIASES[normalized] || null
}

export const getBuiltinActivityDefinition = (activityId) => {
  const normalized = normalizeBuiltinDefinitionId(activityId)
  if (!normalized) return null
  return CLIENT_BUILTIN_BY_ID[normalized] || null
}

export const isBuiltinActivityId = (activityId) => !!getBuiltinActivityDefinition(activityId)
